services:
  web:
    build: .
    image: lucid-minimal-backend:latest
    command: fastapi dev app/main.py --host 0.0.0.0 --port 8000
    volumes:
      - "/lucid-minimal-backend/.venv"
      - ".:/lucid-minimal-backend"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - database
    restart: on-failure

  database:
    image: docker.io/mysql
    env_file:
      - .env

